## Упражнения по библиотеке Numpy

In [171]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [176]:
arr = np.random.randint(0,10,10)
print(arr)
for i in np.where(abs(arr-5.5)<=2.5): # <=> arr>3 and arr<8
       arr[i] = -arr[i]
print(arr)

[9 2 4 1 6 6 4 5 9 7]
[ 9  2 -4  1 -6 -6 -4 -5  9 -7]


**2.** Заменить максимальный элемент случайного массива на 0

In [177]:
print(arr)
arr[arr == max(arr)] = 0
print(arr)

[ 9  2 -4  1 -6 -6 -4 -5  9 -7]
[ 0  2 -4  1 -6 -6 -4 -5  0 -7]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [178]:
def cartesian(arrays): 
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    idx = np.indices(shape, dtype=int)
    idx = idx.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        idx[:, n] = arrays[n][idx[:, n]]

    return idx

print(cartesian(([1, 2, 3], [4, 5, 6], [7,8])))

[[1 4 7]
 [1 4 8]
 [1 5 7]
 [1 5 8]
 [1 6 7]
 [1 6 8]
 [2 4 7]
 [2 4 8]
 [2 5 7]
 [2 5 8]
 [2 6 7]
 [2 6 8]
 [3 4 7]
 [3 4 8]
 [3 5 7]
 [3 5 8]
 [3 6 7]
 [3 6 8]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [179]:
a = np.random.randint(0,5,(8,3))
b = np.random.randint(0,5,(2,2))
print(a)
print(20*'-')
print(b)
print(20*'-')
mask = [np.isin(row,b[0]).any() and np.isin(row,b[1]).any() for row in a]
print(a[mask])

[[4 0 0]
 [0 2 2]
 [1 0 0]
 [3 4 4]
 [0 3 1]
 [2 0 3]
 [2 2 4]
 [3 3 0]]
--------------------
[[4 1]
 [0 3]]
--------------------
[[4 0 0]
 [1 0 0]
 [3 4 4]
 [0 3 1]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [183]:
arr = np.random.randint(0,3,(10,3))
print(arr)
print(10*"-")

i = 0
while i < np.size(arr,axis=0):
    if len(np.unique(arr[i]))==1:
        arr = np.delete(arr,i, axis=0)
        i -= 1
    i += 1
     
print(arr)

[[2 2 2]
 [1 1 0]
 [0 1 2]
 [1 2 1]
 [2 1 1]
 [2 2 1]
 [0 0 2]
 [2 1 1]
 [2 2 2]
 [1 2 0]]
----------
[[1 1 0]
 [0 1 2]
 [1 2 1]
 [2 1 1]
 [2 2 1]
 [0 0 2]
 [2 1 1]
 [1 2 0]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [25]:
arr = np.array([[1, 8, 3, 3, 4],
       [1, 8, 9, 9, 4],
       [1, 8, 3, 3, 4],
       [1, 8, 3, 3, 4],
       [1, 8, 0, 3, 4],
       [1, 8, 9, 9, 4]])
print(arr)
print(10*'-')
arr = np.unique(arr, axis=0)
print(arr)

[[1 8 3 3 4]
 [1 8 9 9 4]
 [1 8 3 3 4]
 [1 8 3 3 4]
 [1 8 0 3 4]
 [1 8 9 9 4]]
----------
[[1 8 0 3 4]
 [1 8 3 3 4]
 [1 8 9 9 4]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [38]:
# 1st way
x1 = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
p1 = 1
for i in range(len(x1)):
    for j in range(len(x1[i])):
        if i == j and x1[i][j] != 0:
            p1 *= x1[i][j]
print("p1 = ",p1)

# 2nd way
x2 = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
a = x2.diagonal()
p2 = np.prod(a[a!=0])
print("p2 = ", p2)

p1 =  3
p2 =  3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [43]:
# 1nd way
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
print(sorted(x)==sorted(y))

# 2n way
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
print(x.sort() == y.sort())

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [184]:
# 1st way
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
new_arr = []
for i in range(len(x)):
    if x[i] == 0 and i != len(x)-1:
        new_arr.append(x[i+1])
maximum = max(new_arr)
print(maximum)

5


In [185]:
# 2nd way
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
a = np.where(x[:len(x)-1] == 0)[0] + 1
maximum = max(x[a])
print(maximum)

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [53]:
# 1st way
x = [2, 2, 2, 3, 3, 3, 5]
nums = [x[0]]
counts = [0]
for i in range(len(x)):
    if nums[-1] != x[i]:
        nums.append(x[i])
        counts.append(1)
    else:
        counts[-1] += 1
        
print("Numbers: ", nums)
print("Quantity of each number: ", counts)

Numbers:  [2, 3, 5]
Quantity of each number:  [3, 3, 1]


In [186]:
# 2nd way
x = np.array([2, 2, 2, 3, 3, 3, 5,])
print(np.unique(x, return_counts=True))

(array([2, 3, 5]), array([3, 3, 1], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [196]:
# 1st way
import time 
start_time = time.time()

x = np.random.randint(0, 10, (3, 2))
print(x)
y = np.random.randint(0, 10, (3, 2))
print(y)

res = []
dim = len(x[0])
for j in range(len(y)):
    res.append([])
    for i in range(len(x)):
        s = 0
        for k in range(dim):
            s += (x[i][k]-y[j][k])**2
        res[j].append(round(s**(1/2),2))
print(res)

print(f"Time of executing: {(time.time() - start_time)*1000} ms")



[[1 7]
 [4 1]
 [9 2]]
[[2 9]
 [5 3]
 [4 5]]
[[2.24, 8.25, 9.9], [5.66, 2.24, 4.12], [3.61, 4.0, 5.83]]
Time of executing: 1.9965171813964844 ms


_______
________

In [197]:
# 2nd way
start_time = time.time() 

x = np.random.randint(0, 10, (3, 2))
print(x)
y = np.random.randint(0, 10, (3, 2))
print(y)
x1 = np.repeat(x,len(y),axis=0).reshape(len(x),-1,2)
y1 = np.repeat(y, len(x), axis=0).reshape(len(y),-1,2).transpose(1,0,2)
res = np.sqrt(np.sum((x1 - y1)**2, axis=2)).round(2)
print(res)

print(f"Time of executing: {(time.time() - start_time)*1000} ms")

[[1 2]
 [7 8]
 [6 5]]
[[7 4]
 [1 2]
 [8 1]]
[[6.32 0.   7.07]
 [4.   8.49 7.07]
 [1.41 5.83 4.47]]
Time of executing: 2.9973983764648438 ms


In [195]:
# 3rd way
from scipy import spatial

start_time = time.time() 

x = np.random.randint(0, 10, (3, 2))
print(x)
y = np.random.randint(0, 10, (3, 2))
print(y)

res = spatial.distance.cdist(x, y)
print(res)

print(f"Time of executing: {(time.time() - start_time)*1000} ms")

[[0 4]
 [3 8]
 [6 9]]
[[4 2]
 [5 8]
 [1 9]]
[[4.47213595 6.40312424 5.09901951]
 [6.08276253 2.         2.23606798]
 [7.28010989 1.41421356 5.        ]]
Time of executing: 1.9977092742919922 ms


* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [77]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [29]:
calorie_stats = np.loadtxt("./cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [30]:
average_calories = np.round(np.mean(calorie_stats)) - 60
print(average_calories)

47.0


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [76]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [78]:
median_calories = np.median(calorie_stats_sorted)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [89]:
for i in range(101):
    percentile_value = np.percentile(calorie_stats, i)
    if percentile_value > 60:
        nth_percentile = i
        break
print("nth_persentile = ", nth_percentile, "%")

nth_persentile =  4 %


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [94]:
more_calories = np.round(100*len(calorie_stats[calorie_stats > 60])/len(calorie_stats))
print(more_calories,"%")

96.0 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [95]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [97]:
# Стандартное отклонение в 19.4 каллории говорит об умеренном разбросе данных, а значит данные более-менее равномерны и им 
# можно доверять.
# Посмотрев на все полученные данные можно сказать, что батончики CrunchieMunchies намного опережают большинство других 
# конкурентов по уровню каллорийности, а каллорийность является ведущей характеристикой для спортивных батончиков. Таким образом можно 
# утверждать, что батончики CrunchieMunchies заимеют успех в продажах при хорошем маркетинге. Специалистам по маркентигу следует 
# следует сделать акцент на том, насколько меньше каллорийность в CrunchieMunchies по сравнению со средним батончиком, а также
# на то, что батончик опережает по каллорийности 96% остальных батончиков.